services:
  - type: web
    name: atlantic-city-casino
    env: python
    buildCommand: "./build.sh"
    startCommand: "uvicorn api:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: RENDER
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: atlantic-city-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: LOG_LEVEL
        value: "INFO"

databases:
  - name: atlantic-city-db
    databaseName: atlantic_city_casino
    user: casino_user